/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    MovieCard: typeof import('./src/components/MovieCard.vue')['default']
    MovieCardSkeleton: typeof import('./src/components/MovieCardSkeleton.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeatPicker: typeof import('./src/components/SeatPicker.vue')['default']
    ShowtimePicker: typeof import('./src/components/ShowtimePicker.vue')['default']
    SignupForm: typeof import('./src/components/auth/SignupForm.vue')['default']
  }
}
